### ISSUE TITLE
WebApp Java Servlet: Nothing in the readme file

### ISSUE THREAD

**Issue by paulioceano** [auth0-samples/auth0-servlet-sample#17]
In the github repo, the project has 2 README.md files, one inside the folder 01-login where all the instructions are correct, but the other readme file is outside this folder and is empty (https://github.com/auth0-samples/auth0-servlet-sample/blob/master/README.md).

![capture-for-jira-screenshot-20171207-123750-844](https://user-images.githubusercontent.com/15818783/33771318-ff019a02-dc06-11e7-8f0d-a8cdd3e4966c.png)

**Comment by aaguiarz** [comment]
Fixed in https://github.com/auth0-samples/auth0-servlet-sample/pull/16
