### ISSUE TITLE
black page

### ISSUE THREAD

**Issue by panicou** [auth0-samples/auth0-servlet-sample#3]
hello,
i  changed my auth0 settings and compiled the project  , but i get only the grey modal top right saying i need to login. Lock doesn't appear at all.

On firebug console i get an error : 

SyntaxError: identifier starts immediately after numeric literal
state: nonce=31D6BFC8F37C974E821D9DE73FA6CDD5,

login (line 24, col 27

Kind Regards,

**Comment by arcseldon** [comment]
@panicou - Hello, apologies for the late reply. Please let me know if you would like some assistance / managed to resolve the issue you were facing as reported above. Be happy to help you out.

**Comment by mpaktiti** [comment]
Hello @panicou Do you face this issue still? Can we help?

**Comment by mpaktiti** [comment]
Hi @panicou , we will close this issue since it's inactive for some time. Feel free to reopen or register a new one if you still have issues. Thanks!
